### PR TITLE
Bugsmash - scroll position is not reset when navigating to a differen…

### PR DESCRIPTION
**Pull request by kaseywright**
…t resource page.

### CODE REVIEW

**Comment by MrGrinst** [comment]
@kaseywright looks like we also need special handling for Fia content (or more broadly step-based content) where the user can navigate between steps:
https://github.com/BiblioNexusStudio/content-manager-web/blob/master//Users/kylegrinstead/Developer/content-manager-web/src/lib/components/resources/content-components/Text.svelte#L60

**Comment by kaseywright** [comment]
As a note: when viewing Fia content, the scroll position when going from a step that has 'short' content to a step that has 'long' content, the scroll position should be reset.

**Comment by kaseywright** [comment]
Upon further testing of Fia content stepping, I found that the browser remembers the last position of the divs. If we reset the scroll position for the scroll sync, it causes the divs to reset their position on mouseover which could be unexpected for the user. I'd say send what we have and look for user feedback.

**Comment by jwinston-bn** [comment]
No one is editing FIA content in Aquifer right now.

**Pull request merged**
